# Generated by Django 4.2 on 2024-12-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='fotos_articulos/')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('nivel', models.IntegerField(default=0)),
                ('nomenclatura', models.CharField(max_length=25)),
                ('padre_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='padre', to='almacen.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articulos', to='almacen.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('Ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ubicacion', to='almacen.ubicacion')),
                ('articulos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articulo', to='almacen.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articuloe', to='almacen.articulo')),
            ],
        ),
    ]
