# Generated by Django 4.2 on 2025-01-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_articulo_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'managed': True, 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='foto',
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='fotosArticulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='fotos_articulos/')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articuloFoto', to='almacen.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='bodega',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bodega', to='almacen.bodega'),
            preserve_default=False,
        ),
    ]
