# Generated by Django 4.2 on 2025-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_bodega_alter_articulo_options_remove_articulo_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotosarticulos',
            options={'managed': True, 'verbose_name': 'Fotos de Articulos', 'verbose_name_plural': 'Fotos de Articulos'},
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_de_medida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
