# Generated by Django 4.2 on 2025-10-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_fotosarticulos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
