# Generated by Django 4.2 on 2025-10-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_reestructurar_ubicaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ('bodega__nombre', 'nivel', 'numero', 'nombre'), 'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
