# Generated by Django 4.2 on 2025-10-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_restore_numero_column'),
        ('almacen', '0009_marca_unidadmedida'),
    ]

    operations = [
    ]
