# Generated by Django 4.2 on 2025-10-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_merge_20251017_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('ESTANTE', 'Estante'), ('ESTIBA', 'Estiba'), ('PANEL', 'Panel'), ('DIVISION', 'Division'), ('CONTENEDOR', 'Contenedor')], default='ESTANTE', max_length=15),
        ),
    ]
