# Generated by Django 4.2 on 2025-10-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_alter_ubicacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filas', models.PositiveIntegerField(default=6)),
                ('columnas', models.PositiveIntegerField(default=8)),
                ('tamano_celda', models.PositiveIntegerField(default=120)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bodega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_distribucion', to='almacen.bodega')),
            ],
            options={
                'verbose_name': 'Plano de distribucion',
                'verbose_name_plural': 'Planos de distribucion',
            },
        ),
        migrations.CreateModel(
            name='DistribucionUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField(default=1)),
                ('columna', models.PositiveIntegerField(default=1)),
                ('ancho', models.PositiveSmallIntegerField(default=1)),
                ('alto', models.PositiveSmallIntegerField(default=1)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='almacen.planodistribucion')),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_distribucion', to='almacen.ubicacion')),
            ],
            options={
                'verbose_name': 'Distribucion de ubicacion',
                'verbose_name_plural': 'Distribuciones de ubicaciones',
                'ordering': ('fila', 'columna'),
            },
        ),
    ]
