# Generated by Django 4.2 on 2025-10-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_planodistribucion_distribucionubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucionubicacion',
            name='es_pasillo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distribucionubicacion',
            name='nombre_pasillo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='distribucionubicacion',
            name='ubicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plano_distribucion', to='almacen.ubicacion'),
        ),
    ]
