# Generated by Django 4.2 on 2026-10-04 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def asignar_codigos(apps, schema_editor):
    Ubicacion = apps.get_model('almacen', 'Ubicacion')
    for pk in Ubicacion.objects.using(schema_editor.connection.alias).filter(tipo='CONTENEDOR').values_list('pk', flat=True):
        Ubicacion.objects.using(schema_editor.connection.alias).filter(pk=pk).update(codigo_contenedor=f'CONT-{pk:06d}')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacen', '0013_distribucionubicacion_es_pasillo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='codigo_contenedor',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.RunPython(asignar_codigos, migrations.RunPython.noop),
        migrations.CreateModel(
            name='MovimientoContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_origen', models.TextField()),
                ('ruta_destino', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_hacia', to='almacen.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_desde', to='almacen.bodega')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='almacen.ubicacion')),
                ('contenedor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_realizados', to='almacen.ubicacion')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_hacia', to='almacen.ubicacion')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_desde', to='almacen.ubicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de contenedor',
                'verbose_name_plural': 'Movimientos de contenedores',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
