# Generated by Django 4.2 on 2026-10-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_contenedores_moviles'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='almacen.ubicacion'),
        ),
        migrations.AddField(
            model_name='salidas',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='almacen.ubicacion'),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
