# Generated by Django 4.2 on 2026-10-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0015_ubicaciones_entradas_salidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='bodega_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='almacen.bodega'),
        ),
        migrations.AddField(
            model_name='entradas',
            name='codigo_ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entradas',
            name='descripcion_articulo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entradas',
            name='nombre_bodega',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='entradas',
            name='ruta_ubicacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='bodega_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='almacen.bodega'),
        ),
        migrations.AddField(
            model_name='salidas',
            name='codigo_ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salidas',
            name='descripcion_articulo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='nombre_bodega',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='salidas',
            name='ruta_ubicacion',
            field=models.TextField(blank=True),
        ),
    ]
