# Generated by Django 4.2 on 2026-10-05 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacen', '0016_contexto_historico_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('descripcion_articulo', models.TextField()),
                ('nombre_bodega_origen', models.CharField(max_length=30)),
                ('nombre_bodega_destino', models.CharField(max_length=30)),
                ('ruta_origen', models.TextField()),
                ('ruta_destino', models.TextField()),
                ('codigo_origen', models.CharField(max_length=100)),
                ('codigo_destino', models.CharField(max_length=100)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='almacen.articulo')),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_articulos_hacia', to='almacen.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_articulos_desde', to='almacen.bodega')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_hacia', to='almacen.ubicacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_desde', to='almacen.ubicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='trasladoarticulo',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='traslado_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='trasladoarticulo',
            constraint=models.CheckConstraint(check=models.Q(('origen', models.F('destino')), _negated=True), name='traslado_ubicaciones_distintas'),
        ),
    ]
